defaults:
  - model_checkpoint
  - model_checkpoint_best
  - retrieval_callback
  - visualization_callback
  - modality_gap_callback
  - monitor
  - model_summary
  - progress_bar
  - _self_

model_summary:
  max_depth: 1
