# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

modality_gap_callback:
  _target_: src.callbacks.modality_gap.ModalityGap
  every_n_epochs: 1 # number of epochs between checkpoints
