# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint_best:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.ckpt_dir} # directory to save the model file
  verbose: true # verbosity mode
  save_last: true # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: 1 # save k best models (determined by above metric)
  mode: "min" # "max" means higher metric value is better, can be also "min"
  monitor: "loss/val/total_loss/dataloader_idx_0" # metric to monitor for the best model
  auto_insert_metric_name: false # when True, the checkpoints filenames will contain the metric name
  filename: "best_{epoch:02d}_val_loss_{loss/val/total_loss/dataloader_idx_0:.2f}" # custom filename for the checkpoint
  save_weights_only: false # if True, then only the model’s weights will be saved
  every_n_epochs: 1 # number of epochs between checkpoints