# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

retrieval_callback:
  _target_: src.callbacks.retrieval.RetrievalEvaluation
  every_n_epochs: 1 # number of epochs between checkpoints
  distance: 'cosine' # distance metric to use for retrieval
